# Generated by Django 4.1.7 on 2023-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_product_price_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
